---
title: "References"
---

#### Peter Mcphee, "Living the French Revolution 1789-1799" Palgrave Macmillan, 10 Oct 2006

This text was used for information on the reforms put in place. Some examples would be of the education system reforms and tax reforms. As well as the abolition of feudalism.

#### James M Anderson, "Daily life during the French Revolution" Greenwood Press, 28 Feb 2007

This book was used to gather research about French life during the French revolution. It was used for information about religion and its relationship to the French citizen.

#### Doug Shultz,"The French Revolution" Partisan Pictures, 17 Jan 2005

This documentary was used to gain a bit of general knowledge. It was used to understand the events that happened and the main people involved in the French Revolution.

#### Dan Edelstein, Micheal Keller "French Revolution Digital Archives" Stanford University Libraries, https://exhibits.stanford.edu/frenchrevolution , 28 Jan 2014

This website was used to gather information about the long term affects of the Revolution. It was also used for information on events like the Terror.

#### Lynn Hunt & Jack Censer, "Liberty Equality Fraternity: Exploring the French Revolution" Roy Rozenweig Center for History and New Media, revolution.chnm.org, 1 June 1997

This website was used to find paintings, drawings and stamps that were made during the revolution. It shows events and what people may have looked like.

#### Rev W Herbert Burk "France and the American Revolution" Museum of the American Revolution, https://www.amrevmuseum.org/france-and-the-american-revolution, 1 April 2017

This website was used to understand some of the reasons Frannce was indebt. It also showed why France supported the American Revolution. 

#### "History|Chateau de Versailles" etablissement public de chateau du musee et du domaine national de Versailles, Jan 31 2017, https://chateauversailles/history/great-characters/louis-xvi 

This site was used for general information on the king and Queen. It tells their backgrounds.

#### "French Revolution|history,summary,timeline,causes and facts|brittanica" Encyclopedia Britannica inc, Oct 19 1999, https://www.britannica.com/event/French-Revolution

This website was used to gain general knowledge of events. It helped as a start to understand the topic

#### "Louis XVI Early Years" The history guild, https://historyguild.org/Louis-xvis-early-years/?srsltid=AfmBOornDZXvcjse7UBjpG9JuCeF4SuHl25eOa4uj9TVmPz4OZMaQqia

This site was used to  understand the King Louis XVI past. As well as the Queen Antoinette's background before being married to the king. 

#### "France pension reforms:Macron signs pension age rise to 64 into law", British Broadcasting Corporation ,Dec 15 1997 , https://www.google.com/amp/s/www.bbc.com/news/world-europe-65279818.amp

This site was used briefly to talk about the revolts the French still do today. The 2023 revolt was about the retirement age going up.

#### "At least 195,000 take to streets across France to denounce budget cuts" France Medias Monde,Dec 6 2006 ,https://www.france24.com/en/europe 20251002-anti-government-protests-france

This site was used briefly to talk about the revolts the French do today. This event happened in 2025 about the budget cuts the government wanted to make.