---
title: "The French Revolution (1789-1799)"
---

### Prologue: Prior to the Revolution

King Louis XV's grandson assumed the throne in 1774 at age 19. The grandson, King Louis XVI, was educated but not properly prepared to govern because he was not expected to become king. He was the third in line for the crown until his two older brothers, and father died of tuberculosis. The king soon married a princess for a political alliance with Austria.

The country of France was also still reeling from the seven years' war, and the prospect of the American revolution intrigued them. They supported America due to its possibility of being able to harm Britain. France formed an alliance with America for a couple of reasons, which was political power, interest in its ideals and to get back at their enemy, Britain.

### What sparked the French Revolution?

King Louis XVI was not a great ruler of france like his predecessors. His leadership had caused to go into more debt than it already was, squandering it on extravagant purchases. As well as helping America, not because of kindness but because he wanted to get get back at England to avenge his father. 

King Louis XVI's indecision of important matters of his country created many roblems. 

### What happened during the French revolution?

The people fed up with his rule took a stand and formed a mob at the Bastille. They killed everyone including the one in charge of that establishment, leaving a massive path of bloodshed. This event helped to inspire Jean Paul Marat, a journalist who helped to garner more people to the cause of the revolution using his papers, as well as  William Robespierre, one of the most important people of the revolution which contributed to the Declaration of the Rights of Man and one of the most bloodiest parts of the revolution.

After the seige of the Bastille,a group of people banded together to create a national assembly . This assembly created The Declaration of the Rights of Man,which was inspired by the Magna Carta and The Declaration of Independence. The Declaration of the Rights of Man helped to lay the framework for the future laws of France.

At first, the national assembly wanted a constitutional monarchy:a monarchy in which there are people working alongside the king to control the country.This would later on not be able to come true since the monarchy fought back against them. The people would mob the palace and take the king and queen hostage,moving them all the way to paris,where they stayed in the Tuileries Palace.The king and queen would soon try to flee and try to get help. However, they were caught and soon taken back to the palace. The national assembly soon decided to bring an end to the monarchy after the incident.

Around this time a war started with Austria. Austria was trying to help save the dying monarchy by fighting back against the republic that was starting to form.All men, from peasants to higher ranking individuals joined the fight for their country, which allowed for peasants to start charging more for their services. Eventually after fighting back against Austria , the assembly decide to kill the king and queen using the guilotine: a device that would be an important form of execution. 
With that this was the start of the republic the national assembly wanted.

### Short-Term Reforms from the French Revolution

During these events The National Assembly was working on implementing different laws that would help benefit the French citizens. One of these laws was the outlawing of religion, this was due to the church and the monarchy working very closely together. The church was in a high power position because of their connection and influence over the country. The church also clashed against what the revolution believed in, it viewed the revolution as an enemy to its authority. This affected another law in which it was stated that education would be available to all. However, this was hard to do since there was a lack of educators. Prior to the revolution the church was responsible for providing staff for schools. Many of the schools were owned and staffed by the church. In regions were the school system was succesful, the people were able to find jobs. However, in regions where it wasnt as sucessful there was a major funding crisis for education.

### The French Revolution's Long-Term Impact

The French revolution...

### Conclusion

The French Revolution took place in 1789-1799 as a reaction to the monarchy's irresponsible rule. The revolution changed many times over the years but one thing remained a constant over the years, their quest for equality and their rights as citizens of France. However, that came with many difficulties, some internal like ensuring reforms and dealing with people defying the revolution, as well as external forces like Austria coming to try and help the dying monarchy of Louis XVI and Marie Antonette.