---
title: "Process Paper"
---

I selected this topic because was interested in the history of France. I started with researching background information such as people and places. The topic I chose was the French Revolution; to gain general information I looked for websites that could help. The webites were from history departments of universities like George Mason University and City University of New York. The information I found was mostly about the events like the Terror and the Storming of the Bastille and the important people involved.

I soon scourged my local library for information on the French Revolution. The library did not have many books to use but they did have a documentary available. The documentary helped to provide me details about events and people. The documentary led me to research individuals for their participation in the French Revolution. I also made my search elsewhere for other resources. I founs two books that were really helpful. These books, "Living the French Revolution 1789-1799" by Peter McPhee and "Daily life during the French Revolution" by James M. Anderson helped me narrow what I wanted to focus on. These books helped me understand the laws that were in place and how people were affected. I chose these topics to research because the people were affected by the events of the French Revolution and the people had an affect on its outcome.

After reading through my research and gathering the important events I wanted to work on, I wrote up my paragraphs and began building the National History Day website. While gathering information I was also looking for pictures to include on the website. I chose portraits of important people and pictures of important events. I went to a site called the French Revolution Digital Archive to find stamps and drawings that could be added to my website. I also went to news websites for more current event pictures. I then transferred it to the computer where I spell checked, arranged, and edited my write-up. 

I wrote my sources down into Modern Language Assiociation format so I could create my Annotated Bibliography. I checked if the links worked and if I had written the citations correctly before writing a blurb which was 2-3 sentences long for each one of them. I added the Annotated Bibliography into the website, dedicating a page to it, and checking that the links worked.

Finally, I reviewed my website and ensured I included everything I had researched for my project without leaving anything important out. 
